version: '3'

services:
  # Apache 웹 서버
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=kisia_market
    networks:
      - kisia-network

  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kisia_market
    networks:
      - kisia-network

  # phpMyAdmin (선택사항)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    networks:
      - kisia-network

volumes:
  mysql_data:

networks:
  kisia-network:
    driver: bridge 