services:
  # Apache 웹 서버
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - mailhog
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=kisia_market
    networks:
      - kisia-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # MailHog 웹 UI
      - "1025:1025"  # MailHog SMTP 포트
    networks:
      - kisia-network

  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # 문자셋 설정
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    networks:
      - kisia-network

volumes:
  mysql_data:

networks:
  kisia-network:
    driver: bridge